//4 bit carrylookaheaad adder block 
//4 bit carry look ahead adder will later be rippled to make M-bit adder

//group_p(group propagate)tells whether the cin can pass from bit 0 all the way to the block
//output, if group_p = 1, cin can pass from bit 0 all the way to the block
//outpout

//group_g(group generate) tells the next level whether a cout will be generate
//without needing cin, if group_g = 1, it means a carry-out will be generated
//even without needing cin  
module cla4_block(
  input logic [3:0] a,
  input logic [3:0] b,
  input logic cin,
  output logic [3:0] sum,
  output logic cout,
  output logic group_p,
  output logic group_g
  );

  //4 bit internal propagate signal(p[i] = a[i] XOR b[i])
  //each bit p[i] tells us whether bit i will propagate a carry
  logic [3:0] p;

  //4 bit internal generate signal(a[i] AND b[i])
  //each bit g[i] tells us whether bit i will generate a carry
  logic [3:0] g;

  //5 bit internal carry signal(becaause this is a 4 bit adder, we need
  //5 carry signals)
  //c[0] = carry into bit 0
  //c[1] = carry into bit 1
  //c[2] = carry into bit 2
  //c[3] = carry into bit 3
  //c[4] = carry out of bit 3(cout)
  logic [4:0] c;

  //calculates all 4 propagate bits at once
  assign p = a ^ b;
  //calculate all 4 generate bits at once
  assign g = a & b;

  //calculate carry out without needing to wait for carry propagate through
  //each bit
  assign c[0] = cin;
  //carry into bit 1 when bit 0 generates a carry itself or 
  //it propagates the incoming carry
  assign c[1] = g[0] | 
                (p[0] & c[0]);
  //carry into bit 1 when bit 1 generates a carry itself or
  //bit 1 propagates a caarry generated by bit 0 or
  //bit 1 and bit 0 both propagate the original cin 
  assign c[2] = g[1] | 
                (p[1] & g[0]) |
                (p[1] & p[0] & c[0]);
  //carry into bit 3 when bit 2 generates a carry or
  //bit 2 propagates a carry generated by bit[1]
  //bit 2 and bit 1 propagate a carry generated by bit 0
  //bit 2 and bit 1 and bit 0 all propagate the original cin 
  assign c[3] = g[2] |
                (p[2] & g[1]) |
                (p[2] & p[1] & g[0]) |
                (p[2] & p[1] & p[0] & c[0]);
  //carryout when bit 3 generate a carry or
  //bit 3 propagate a carry generated by bit 2
  //bit 3 and bit 2 propagate a carry generated by bit 1
  //bit 3 and bit 2 and bit 1 propagate a carry generated by bit 0
  //bit 3 and bit 2 and bit 1 and bit 0 propagate the original cin
  assign c[4] = g[3] |
                (p[3] & g[2]) |
                (p[3] & p[2] & g[1]) |
                (p[3] & p[2] & p[1] & g[0]) |
                (p[3] & p[2] & p[1] & p[0] & c[0]);


  //calculate the 4-bit sum
  //sum[i] = a[i] ^ b[i] ^ c[i]
  //whereas p[i] = a[i] ^ b[i]
  assign sum = p ^ c[3:0];

  //connect the final internal carry to the output cout 
  assign cout = c[4];
  //this calculate the group propagate signal
  //the whole 4 bit block propagates carry only if every bit propagates carry
  assign group_p = p[3] & p[2] & p[1] & p[0];
  //this calculates the group generate signal
  //the block generates a carry-out by itself if:
  //bit 3 generates a carry
  //bit 3 propagate a carry generated by bit 2
  //bit 3 and bit 2 propagate a carry generated by bit 1
  //bit 3 and bit 2 and bit 1 propagate a carry generated by bit 0
  assign group_g = g[3] | 
                   (p[3] & g[2]) |
                   (p[3] & p[2] & g[1]) |
                   (p[3] & p[2] & p[1] & g[0]);

endmodule

